API
Rafaellynhah/tech-flix pull request #1
Opened 2021-02-11 19:10 UTC by Rafaellynhah

Create:

Api serie, movie and category

2021-02-11 19:48 UTC, mathelima approved these changes

2021-02-11 20:03 UTC, lucasljoliveira-olist commented on flix/app/views.py
> +    queryset = Category.objects.all()
aqui vc pode adicionar um order_by('<nome do campo>') para organizar os dados

2021-02-11 20:05 UTC, lucasljoliveira-olist approved these changes
Muuuito boom !!!

2021-02-11 20:20 UTC, lucasdario approved these changes

2021-02-11 20:23 UTC, mblopes requested changes

2021-02-11 20:23 UTC, mblopes commented on flix/app/models.py
> +        return self.name
Falta uma linha em branco no final de alguns arquivos

2021-02-12 11:50 UTC, Rafaellynhah commented on flix/app/models.py
> +        return self.name
Ajustado!

2021-02-12 11:52 UTC, Rafaellynhah commented on flix/app/views.py
> +    queryset = Category.objects.all()
Ele fica como default ordenado por id nesse modo, caso queira ordenar por outro campo, dai se utiliza o order_by.

2021-02-12 11:52 UTC, merged